name: Run download.py with incremented version codes on older branch

on:
  workflow_dispatch:  # Manually trigger the workflow in GitHub Actions
    inputs:
      branch:
        description: "Branch to run the workflow on"
        default: "older"
        required: true

jobs:
  run_download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}  # Check out the specified branch

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install asyncio aiohttp google protobuf==3.20.* google-auth requests

      - name: Run download.py
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}  # Inject GitHub secret
        run: |
          python download.py
        continue-on-error: false  # Stop the workflow if this step fails

      - name: Increment version codes in download.py
        if: success()  # Only run if the previous step succeeds
        run: |
          python increment.py

      - name: Commit and push changes
        if: success()  # Only run if the previous steps were successful
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add .
          git commit -m "Updated versions as of $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git push origin ${{ github.event.inputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Trigger workflow on branch
        if: success()  # Only run if the previous steps were successful
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/older.yml/dispatches \
            -d '{"ref":"${{ github.event.inputs.branch }}"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
